# Generated by Django 6.0.4 on 2026-04-17

from django.db import migrations, models


PREDEFINED_JOBS = [
    {
        "code_name": "print_1_to_100",
        "name": "Print Numbers 1 to 100",
        "description": "Prints numbers from 1 to 100 and returns them as output.",
    },
    {
        "code_name": "sort_small_array",
        "name": "Sort Small Array",
        "description": "Sorts a short predefined array of integers and returns the sorted result.",
    },
    {
        "code_name": "sum_1_to_1000",
        "name": "Sum Numbers 1 to 1000",
        "description": "Calculates the sum of integers from 1 to 1000.",
    },
    {
        "code_name": "find_primes_1_to_100",
        "name": "Find Prime Numbers 1 to 100",
        "description": "Finds all prime numbers between 1 and 100 and returns them as an array.",
    },
    {
        "code_name": "division_by_zero",
        "name": "Division by Zero",
        "description": "Intentionally divides by zero to simulate a runtime error.",
    },
    {
        "code_name": "infinite_loop",
        "name": "Infinite Loop",
        "description": "Intentionally runs forever to simulate a stuck or timeout job.",
    },
]


def sync_predefined_jobs(apps, schema_editor):
    Job = apps.get_model("jobqueue", "Job")
    predefined_by_name = {job["name"]: job for job in PREDEFINED_JOBS}
    used_code_names = set()

    for job in Job.objects.order_by("id"):
        predefined_job = predefined_by_name.get(job.name)

        if predefined_job is None or predefined_job["code_name"] in used_code_names:
            job.delete()
            continue

        job.code_name = predefined_job["code_name"]
        job.name = predefined_job["name"]
        job.description = predefined_job["description"]
        job.save(update_fields=["code_name", "name", "description"])
        used_code_names.add(predefined_job["code_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobqueue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="code_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(sync_predefined_jobs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="job",
            name="code_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
