# Generated by Django 6.0.4 on 2026-04-17

import django.db.models.deletion
from django.db import migrations, models


PREDEFINED_JOBS = [
    {
        "code_name": "print_1_to_100",
        "name": "Print Numbers 1 to 100",
        "description": "Prints numbers from 1 to 100 and returns them as output.",
    },
    {
        "code_name": "sort_small_array",
        "name": "Sort Small Array",
        "description": "Sorts a short predefined array of integers and returns the sorted result.",
    },
    {
        "code_name": "sum_1_to_1000",
        "name": "Sum Numbers 1 to 1000",
        "description": "Calculates the sum of integers from 1 to 1000.",
    },
    {
        "code_name": "find_primes_1_to_100",
        "name": "Find Prime Numbers 1 to 100",
        "description": "Finds all prime numbers between 1 and 100 and returns them as an array.",
    },
    {
        "code_name": "division_by_zero",
        "name": "Division by Zero",
        "description": "Intentionally divides by zero to simulate a runtime error.",
    },
    {
        "code_name": "infinite_loop",
        "name": "Infinite Loop",
        "description": "Intentionally runs forever to simulate a stuck or timeout job.",
    },
]


def create_predefined_jobs(apps, schema_editor):
    PredefinedJob = apps.get_model("jobqueue", "PredefinedJob")

    for job_definition in PREDEFINED_JOBS:
        PredefinedJob.objects.update_or_create(
            code_name=job_definition["code_name"],
            defaults={
                "name": job_definition["name"],
                "description": job_definition["description"],
            },
        )


def attach_existing_jobs(apps, schema_editor):
    Job = apps.get_model("jobqueue", "Job")
    PredefinedJob = apps.get_model("jobqueue", "PredefinedJob")

    for job in Job.objects.all():
        try:
            predefined_job = PredefinedJob.objects.get(code_name=job.code_name)
        except PredefinedJob.DoesNotExist:
            job.delete()
            continue

        job.predefined_job_id = predefined_job.id
        job.save(update_fields=["predefined_job"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobqueue", "0002_job_code_name_predefined_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredefinedJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_name", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.RunPython(create_predefined_jobs, migrations.RunPython.noop),
        migrations.AddField(
            model_name="job",
            name="predefined_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="jobqueue.predefinedjob",
            ),
        ),
        migrations.RunPython(attach_existing_jobs, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="job",
            name="code_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="description",
        ),
        migrations.RemoveField(
            model_name="job",
            name="name",
        ),
        migrations.AlterField(
            model_name="job",
            name="predefined_job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="jobqueue.predefinedjob",
            ),
        ),
    ]
