# Generated by Django 6.0.4 on 2026-04-17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobqueue", "0003_predefined_job_and_job_fk"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PredefinedJob",
            new_name="JobDefinition",
        ),
        migrations.RenameModel(
            old_name="Job",
            new_name="JobExecution",
        ),
        migrations.RenameField(
            model_name="jobexecution",
            old_name="predefined_job",
            new_name="job_definition",
        ),
        migrations.RenameField(
            model_name="jobexecution",
            old_name="state",
            new_name="status",
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="result",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="worker_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="output_file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="jobexecution",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="jobexecution",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="job_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="jobqueue.jobdefinition",
            ),
        ),
        migrations.AlterField(
            model_name="jobexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("timeout", "Timeout"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
